
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-gauchoride-s23-5pm-1
owner: ucsb-cs156-s23
repo_name: proj-gauchoride-s23-5pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjczNTc3MjI1","is_bot":false,"login":"TG6S85","name":"Josh"},"headRefName":"josh-issue23","number":26,"title":"jt- added ride entitiy and rideRepo","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-1/pull/26"},{"author":{"id":"MDQ6VXNlcjU5Mjc3NDgy","is_bot":false,"login":"JamesEllenstein","name":"James Ellenstein"},"headRefName":"jamesRiderToggleButton","number":25,"title":"James rider toggle button","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-1/pull/25"},{"author":{"id":"MDQ6VXNlcjcyODQzNzYw","is_bot":false,"login":"zpr-ucsb","name":"Zach Richards"},"headRefName":"Zach-HomePage","number":14,"title":"Added new home page","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-1/pull/14"}]
