
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-gauchoride-s23-5pm-1
owner: ucsb-cs156-s23
repo_name: proj-gauchoride-s23-5pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjU5NDU5MzE0","is_bot":false,"login":"EKF626","name":"Elijah"},"headRefName":"Elijah-RiderToggle","number":22,"title":"ef - added backend for bool rider","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-1/pull/22"},{"author":{"id":"MDQ6VXNlcjc3NDE3MDg3","is_bot":false,"login":"cmfisher606","name":""},"headRefName":"Chris-ToggleDriver","number":20,"title":"cf - added a toggleDriver button to UsersTable.js","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-1/pull/20"},{"author":{"id":"MDQ6VXNlcjcyODQzNzYw","is_bot":false,"login":"zpr-ucsb","name":"Zach Richards"},"headRefName":"Zach-HomePage","number":14,"title":"Added new home page","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-1/pull/14"}]
