
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-gauchoride-s23-5pm-1
owner: ucsb-cs156-s23
repo_name: proj-gauchoride-s23-5pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjcyODQzNzYw","is_bot":false,"login":"zpr-ucsb","name":"Zach Richards"},"headRefName":"Zach-IndividualRidesBackend","number":34,"title":"Zach individual rides backend","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-1/pull/34"},{"author":{"id":"MDQ6VXNlcjU5NDU5MzE0","is_bot":false,"login":"EKF626","name":"Elijah"},"headRefName":"Elijah-GetRidersDrivers","number":32,"title":"ef - Added get riders and get drivers plus tests","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-1/pull/32"},{"author":{"id":"MDQ6VXNlcjc3NDE3MDg3","is_bot":false,"login":"cmfisher606","name":""},"headRefName":"Chris-NavBlue","number":31,"title":"cf - Added a blue color to the navbar","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-1/pull/31"},{"author":{"id":"MDQ6VXNlcjU5Mjc3NDgy","is_bot":false,"login":"JamesEllenstein","name":"James Ellenstein"},"headRefName":"jamesRiderToggleButton","number":25,"title":"James rider toggle button","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-1/pull/25"}]
