
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-gauchoride-s23-5pm-1
owner: ucsb-cs156-s23
repo_name: proj-gauchoride-s23-5pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjU5NDU5MzE0","is_bot":false,"login":"EKF626","name":"Elijah"},"headRefName":"Elijah-ToggleWheelchair","number":46,"title":"ef -  toggle wheelchair backend","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-1/pull/46"},{"author":{"id":"MDQ6VXNlcjgzNzk0NzE0","is_bot":false,"login":"vikram-elango","name":""},"headRefName":"Vikram-RiderForm","number":42,"title":"ve- added RideForm, RideForm stories, RideForm test and rideFixtures","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-1/pull/42"},{"author":{"id":"MDQ6VXNlcjU5NDU5MzE0","is_bot":false,"login":"EKF626","name":"Elijah"},"headRefName":"Elijah-ChangePronouns","number":38,"title":"ef - add user pronouns, change pronouns endpoint, and test","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-1/pull/38"},{"author":{"id":"MDQ6VXNlcjczNTc3MjI1","is_bot":false,"login":"TG6S85","name":"Josh"},"headRefName":"josh-issue35","number":37,"title":"jt-fixed raw json display on profile page","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-1/pull/37"},{"author":{"id":"MDQ6VXNlcjcyODQzNzYw","is_bot":false,"login":"zpr-ucsb","name":"Zach Richards"},"headRefName":"Zach-IndividualRidesBackend","number":34,"title":"ZR - Individual Rides Backend","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-1/pull/34"}]
